### ISSUE TITLE
Blown away by what you've done!

### ISSUE THREAD

**Issue by PySimpleGUI** [dymaxionkim/FGPG2#1]
❤ that you not only included a screenshot, but you included one for PyDroid3 too!

I've never seen a repo that shows a PySimpleGUI program running on PyDroid3.  How exciting to run across your work!

![image](https://user-images.githubusercontent.com/46163555/145720359-6b537994-a33e-48fc-bc2c-8f1038b4a829.png)

Brilliant!

**Comment by PySimpleGUI** [comment]
Since you use PyInstaller, you may like the GUI front-end that `psgcompiler` added.

**Comment by dymaxionkim** [comment]
Thank you for your attention!
